---
title: "US Counties"
output: html_notebook
---

Scratch for now, but will turn into correlation for counties
https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv

```{r, echo = FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
options(tidyverse.quiet = TRUE)
library(plyr)
library(tidyverse)
library(readxl)
library(rvest)
library(here)
```

Read in the county population and area data:
```{r}

# first, grab all the 50 state url
state_urls <- paste0(
  "https://tigerweb.geo.census.gov/tigerwebmain/Files/tab20/tigerweb_tab20_county_2010_",
  tolower(state.abb),
  ".html"
)

# for some reason, data on GA, HI, and ID don't exist...
state_urls <- state_urls[-c(10:12)]

# these are displayed as an html table, so use `rvest` to translate to dataframe.
county_areas_list <-
  lapply(state_urls, function(url) {
    (
      as.data.frame(html_table(read_html(url), fill = TRUE)) %>%
        select(BASENAME, NAME, POP100, AREALAND) %>%
        mutate(AREALAND = AREALAND / 2, 589, 988) %>% # square meters to square miles conversion
        mutate(pop_density = POP100 / AREALAND)
    )
  })

names(county_areas_list) <- state.name[-c(10:12)]

# Now, I'd like to turn this list into a dataframe
# I prefer this tidy call over a do.call
county_areas <- plyr::ldply(county_areas_list, data.frame) %>%
  select(-c(X589, X988, NAME, POP100, AREALAND)) %>%
  dplyr::rename(
    state = .id,
    county = BASENAME,
  ) %>%
  identity() # fin
```

Next, read in the county covid data:
```{r}
covid <- read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv") %>%

  # get rid of some of these identifiers. Would be nice to join on FIPS,
  # but my county population area doesn't have FIPS!
  select(-c(UID, iso2, iso3, code3, FIPS, Country_Region, Lat, Long_, Combined_Key)) %>%
  dplyr::rename(
    county = Admin2,
    state = Province_State
  ) %>%

  # Recall that there is no population density data for thise states :(
  filter(!state %in% c("Georgia", "Florida", "Idaho")) %>%
  identity()


# Split this into a list, with one element per state:
# covid_list <- split(covid, covid$Province_State)
```

Now, we have two dataframes and can join them together!
```{r}
county_level_data <- plyr::join(
  x = county_areas,
  y = covid,
  by = c("county", "state"),
  type = "right",
  match = "all"
) %>%

  # the covid data contains some US territories. Drop any rows with no pop data
  drop_na(pop_density) %>%
  identity()
```

mess with plots
```{r}

```

